/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Pokemon {
  version: number;
  id: number;
  num: string;
  name: string;
  img: string;
  type: {
    [k: string]: unknown;
  }[];
  height: string;
  weight: string;
  candy: string;
  candy_count: number;
  egg: string;
  spawn_chance: number;
  avg_spawns: number;
  spawn_time: string;
  multipliers: {
    [k: string]: unknown;
  }[];
  weaknesses: {
    [k: string]: unknown;
  }[];
  next_evolution: [
    {
      num: string;
      name: string;
      [k: string]: unknown;
    },
    ...{
      num: string;
      name: string;
      [k: string]: unknown;
    }[]
  ];
  [k: string]: unknown;
}
