#!/usr/bin/env bash

npm run start:cmd:list

npm run start:cmd:jp2acustom --banner="CHRIS()" --font="cuddly"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="carebear"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="knight4"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="tcb"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="megadeth"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="16X16-F6"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="16X16-F7"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="bennyfnt"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="fantfont"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="candyfntr"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="08X08-F5"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="32X32-F5"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="aura3fntr"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="axxis"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="cebit2_f"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="dr_satan"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="font199r"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="font205"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="font254r"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="mdethfnt"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="arrakis"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="bubsy"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="medway_fr"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="megamin"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="mistyfntr"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="mpocketf"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="outlfont"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="replic_1"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="soundemor"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="tcc1"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="st_adm"
npm run start:cmd:jp2acustom --banner="CHRIS()" --font="wayne_3d"

