set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list


compose-up:
  docker compose up --build 

compose-down:
  docker compose --profile all down

compose-ps:
  docker compose ps 

compose-shell service='redisdb':
  docker compose exec -it {{ service }} bash

compose-logs service='redisdb':
  docker compose logs {{ service }} 
  
