/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Book {
  author: Author;
  title: string;
  publisher: string;
  [k: string]: unknown;
}
export interface Author {
  allOf?: [
    {
      type: "object";
      properties: {
        name: {type: "string"};
        preferredName: {type: "string"};
        age: {type: "string"};
        gender: {enum: ["male", "female", "other"]};
      };
      required: ["name", "preferredName", "age", "gender"];
      additionalProperties: true;
    }
  ];
  [k: string]: unknown;
}
