---
to: <%= name %>/justfile
---
#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list

publish:
  #!/usr/bin/env bash
  set -eufo pipefail

  echo "*************************************"
  echo "** Publish"
  echo "*************************************"

  npm publish

package:
  #!/usr/bin/env bash
  set -eufo pipefail
  mkdir -p ./out
  
  npm view <%= name %> dist.tarball      
  npm pack --pack-destination ./out <%= name %>

