apiVersion: skaffold/v2beta29 
kind: Config
metadata:
  name: -skaffold

build:
  artifacts:
  - image: 25_s3_monitor
    sync: 
      infer: ["skaffold.yaml", "Dockerfile", "public/**", "src/**", "routes/**", "tests/**", "package*.*", "jest.config.js", ".prettier"] 
    custom:
      buildCommand: |
        docker buildx build --progress=plain --target withprofile --build-arg AWS_PROFILE=$AWS_PROFILE --build-arg AWS_REGION=$AWS_REGION --build-context profile=/Users/${USER}/.aws -t $IMAGE . 

deploy:
  docker:
    # docker compose not supported yet
    useCompose: false
    images: [25_s3_monitor]

portForward:
  - resourceType: container
    resourceName: 25_s3_monitor
    port: 8000
    localPort: 8000