services:

  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data      
    networks:
      - service_bridge    
    profiles: [backend]  

  redis-cli:
    build: ./redis-cli
    depends_on:
      - "redis"
    environment:
      - REDIS_HOSTNAME=redis
    networks:
      - service_bridge    
    profiles: [backend]  


networks:
    service_bridge:
        driver: bridge        